### ISSUE TITLE
Why is the UUID of this package "00000000-1111-2222-3333-4444444444444"?

### ISSUE THREAD

**Issue by kimikage** [pfitzseb/REPLTreeViews.jl#8]
This may not be a practical problem, but this defeats the purpose of UUIDs.
https://github.com/pfitzseb/REPLTreeViews.jl/blob/969f04ce641d137ad9c4231f490a362a0fbdf8a2/Project.toml#L1-L3

**Comment by pfitzseb** [comment]
Excellent question. Probably to check if anyone would notice/whether registry CI requires valid uuid4s. "Luckily" we're guaranteed this won't clash with a "proper" uuid, because it's not valid.
